/**
 * @overview Static native DOM workbench for real Remote Lab scenarios and DevTools.
 * @author AEPKILL
 * @created 2026-09-10 00:00:00
 */

export const WORKBENCH_HTML = `
<header class="app-header">
 <div class="brand"><span class="logo">h/</span><strong>remote lab</strong><span class="muted">/ WebSocket</span></div>
 <div class="connection"><span id="peer-name">Browser ⇄ Node</span><strong id="transport" role="status">Connecting</strong><button id="theme" class="icon-button" aria-label="切换深浅主题" title="切换深浅主题">◐</button></div>
</header>
<main>
 <div class="workspace">
  <nav class="scenarios" aria-label="能力场景"><small>EXPLORE / 09</small>
   <button data-scenario="unary" aria-pressed="true"><span>01</span>双向调用</button>
   <button data-scenario="cancel" aria-pressed="false"><span>02</span>取消与调试</button>
   <button data-scenario="recovery" aria-pressed="false"><span>03</span>断线与恢复</button>
   <button data-scenario="peers" aria-pressed="false"><span>04</span>多 Peer 调度</button>
   <button data-scenario="exposure" aria-pressed="false"><span>05</span>暴露与撤销</button>
   <button data-scenario="values" aria-pressed="false"><span>06</span>值模型与边界</button>
   <button data-scenario="errors" aria-pressed="false"><span>07</span>错误与观测</button>
   <button data-scenario="shutdown" aria-pressed="false"><span>08</span>关闭与资源</button>
   <button data-scenario="adapter" aria-pressed="false"><span>09</span>Adapter 与合规</button>
   <div class="sidebar-note">真实 WebSocket<br>双向 unary RPC<br><span class="live-dot"></span> application instrumentation</div>
  </nav>
  <div class="business">
   <section data-scene="unary">
    <div class="eyebrow">01 / BIDIRECTIONAL RPC</div><h1>调用上面的方法，<br class="mobile-break">观察下面发生了什么。</h1><p class="intro">一个业务操作，联动调用网络、数据流、处理器暂停点和控制台。</p>
    <div class="business-grid"><form id="quote-form" class="inline-form"><label>起点<input id="from" value="上海" maxlength="80" required></label><label>终点<input id="to" value="杭州" maxlength="80" required></label><label>重量 / kg<input id="weight" type="number" min="0.1" max="100" step="0.1" value="2.5" required></label><button class="primary" data-needs-peer type="submit">执行 quote →</button></form><div class="quote-result"><small>shipping.quote · 示例运费</small><strong id="quote-result">¥ —</strong><small>真实返回值 → Network / Payload</small></div></div>
    <details class="greeting-details"><summary>并发 greeting & Node → Browser 回调</summary><form id="greeting-form" class="inline-form"><label>Name<input id="name" value="Ada" maxlength="80" required></label><label>延迟 / ms<input id="delay" type="number" min="0" max="10000" step="100" value="1500" required></label><button data-needs-peer type="submit">Send greeting</button><button data-needs-peer id="burst" type="button">Send 3 together</button></form><div class="callback"><span>Node → Browser</span><strong id="callback" aria-live="polite">等待反向调用…</strong></div><ol id="results" class="result-list" aria-live="polite"></ol></details>
   </section>
   <section data-scene="cancel" hidden><div class="eyebrow">02 / CANCELLATION & COOPERATIVE DEBUGGING</div><h1>暂停业务，生命周期继续。</h1><p class="intro">报表处理器支持协作暂停。取消只结束调用端等待，不回滚已经发生的工作。</p><div class="inline-form"><label>处理时间 / ms<input id="report-delay" type="number" min="0" max="10000" value="3000"></label><button id="report-start" data-needs-peer class="primary">启动长任务</button><button id="report-timeout" data-needs-peer>500 ms 应用超时</button><button id="report-pause" data-needs-peer>启动并暂停</button><button id="report-cancel" disabled>取消等待</button><button id="report-resume" data-needs-peer disabled>▶ 继续处理器</button></div><p id="report-result" class="scenario-result" role="status">启动后查看 Network 调用结果与 Sources 业务状态。</p></section>
   <section data-scene="recovery" hidden><div class="eyebrow">03 / RETAINED SESSION</div><h1>替换连接，保留这一次调用。</h1><p class="intro">关闭当前真实 WebSocket，监督器会尝试续接。Peer 和已解析的 facade 保持同一引用。</p><div class="actions"><button id="disconnect" data-needs-peer class="primary">断开 WebSocket</button><button id="recovery-report" data-needs-peer>启动 3 秒报表后断线</button><button id="expire" data-needs-peer>阻断重连 · 5 秒恢复到期</button><button id="allow-reconnect">允许后续重连</button></div><div class="state-strip"><div><small>PEER / 权威状态</small><strong id="recovery-state">connecting</strong></div><div><small>SUPERVISOR / 尝试策略</small><strong id="recovery-supervisor">idle</strong></div><div><small>HANDLER ENTRIES / 应用计数</small><strong id="handler-entries">0</strong></div></div><p class="help">到期演练会终止本 Session；请重新加载创建新 Session。已接纳调用的结果可能为 outcome-unknown，不能据此盲目重发。</p></section>
   <section data-scene="peers" hidden><div class="eyebrow">04 / MULTIPLE PEERS</div><h1>一个 Node，多个独立对等端。</h1><p class="intro">每个标签页拥有自己的 Peer。定向回调与群发都经真实 RPC，群发由示例应用组合。</p><div class="inline-form"><button id="open-peer">↗ 打开第二个浏览器 Peer</button><label>目标 Peer<select id="peer-select" aria-label="目标 Peer"></select></label><label>消息<input id="peer-message" value="Hello from Node" maxlength="120"></label><button id="peer-callback" data-needs-peer class="primary">定向回调</button><button id="peer-fanout" data-needs-peer>群发所有 Peer</button></div><pre id="peers-result" class="scenario-result">等待 Peer 快照…</pre></section>
   <section data-scene="exposure" hidden><div class="eyebrow">05 / DESCRIPTOR & EXPOSURE</div><h1>开放什么，由合约说了算。</h1><p class="intro">撤销控制影响未来调用。Acceptor 全局路由与每个 Peer 的独立路由分开管理。</p><div class="actions"><button id="toggle-global" data-needs-peer>撤销全局 shipping</button><button id="test-shipping" data-needs-peer>调用 shipping.quote</button><button id="test-local" data-needs-peer>调用本 Peer inspect</button><button id="exposure-conflict" data-needs-peer>触发同名暴露冲突</button></div><div id="peer-exposures" class="peer-exposures"></div><p id="exposure-result" class="scenario-result" role="status">实际路由与白名单同时显示在 Services。</p></section>
   <section data-scene="values" hidden><div class="eyebrow">06 / APPLICATION VALUE BOUNDARY</div><h1>只让明确的数据穿过边界。</h1><p class="intro">合法值经 echo 往返。非法值由 Remote 拒绝；APP 记录不等于已创建 RPC 调用。</p><div class="inline-form"><label class="wide-field">JSON 数据<textarea id="value-json" rows="2" spellcheck="false">{"message":"hello","items":[1,true,null]}</textarea></label><button id="value-valid" data-needs-peer class="primary">echo 合法 JSON</button></div><div class="actions"><button data-value="date" data-needs-peer>Date</button><button data-value="undefined" data-needs-peer>嵌套 undefined</button><button data-value="cycle" data-needs-peer>循环引用</button><button data-value="large" data-needs-peer>2 MiB 字符串</button></div><p id="value-result" class="scenario-result" role="status">参数与结果由示例显式采集，摘要有界。</p></section>
   <section data-scene="errors" hidden><div class="eyebrow">07 / ERROR BOUNDARIES</div><h1>失败有边界，结果有依据。</h1><p class="intro">比较真实 handler-failed、unknown-service 与 unknown-method。远端错误消息和堆栈不进入安全 RPC 事件。</p><div class="actions"><button id="handler-fail" data-needs-peer class="primary">处理器抛错</button><button id="unknown-service" data-needs-peer>未知 service</button><button id="unknown-method" data-needs-peer>未知 method</button></div><p id="error-result" class="scenario-result" role="status">错误只终止对应调用；连接状态独立显示。</p></section>
   <section data-scene="shutdown" hidden><div class="eyebrow">08 / OWNER LIFETIME</div><h1>给在途工作一个明确的结尾。</h1><p class="intro">先停止重连监督，再排空或强制关闭 Connector。终止后重新加载页面创建新会话。</p><div class="actions"><button id="shutdown" class="primary">Graceful shutdown</button><button id="force-close" class="danger">Forced close</button><button id="reload">重新加载</button><button id="capacity-run" data-needs-peer>12 个并发调用 · 容量演练</button></div><p class="help">创建时配置：8 pending invocations / Session · recovery grace 5 s · binding attempt 3 s。演练返回每条调用实际结果，接受数量取决于当时状态。</p><pre id="capacity-result" class="scenario-result">尚未运行容量演练。</pre><p class="help">可以先启动长任务再切换到此处比较结果。关闭会停止 HTTP 观测轮询并保留最后快照。</p></section>
   <section data-scene="adapter" hidden><div class="eyebrow">09 / ADAPTER & CONFORMANCE</div><h1>字节通道，有清晰的边界。</h1><p class="intro">本页使用独立 @husky-di/remote-websocket Adapter。send 完成只表示本地接纳，不证明远端接收或处理完成。</p><div class="adapter-grid"><div><small>CONNECTION-LEVEL TRANSPORT</small><pre id="transport-summary">等待真实字节观测…</pre><p class="help">字节数属于连接；不分摊给调用，不解码或展示握手凭证。</p></div><div><small>在仓库根目录执行 / 本页未运行合规测试</small><pre class="command">pnpm --filter @husky-di/remote-websocket test</pre><p class="help">Adapter / Protocol conformance 由 @husky-di/remote/conformance 提供。公开入口：@husky-di/remote/transport（Connection / Adapter）；@husky-di/remote/protocol（可替换 Protocol）。实际合规报告以包测试为准。</p></div></div></section>
   <div class="notice-row"><span id="notice" role="status">正在连接本地 Node 服务…</span><span class="muted">Supervisor: <span id="supervisor">idle</span></span></div>
  </div>
 </div>
 <section class="dock" aria-label="Remote DevTools">
  <nav class="dock-tabs" aria-label="DevTools 面板"><strong>▣ <span>Remote DevTools</span></strong><button data-panel="Network" aria-pressed="true">Network</button><button data-panel="Flow" aria-pressed="false">Flow</button><button data-panel="Sources" aria-pressed="false">Sources</button><button data-panel="Services" aria-pressed="false">Services</button><button data-panel="Console" aria-pressed="false">Console</button><span class="dock-note">Docked to bottom</span></nav>
  <div class="toolbar"><span class="recording">● 记录中</span><label><span class="sr-only">按名称筛选调用</span><input id="call-filter" type="search" placeholder="Filter service / method" autocomplete="off"></label><select id="side-filter" aria-label="按端筛选"><option value="all">All sides</option><option>Browser</option><option>Node</option></select><select id="status-filter" aria-label="按结果筛选"><option value="all">All outcomes</option><option value="pending">pending</option><option value="fulfilled">fulfilled</option><option value="failed">failed</option></select><label class="check"><input id="show-payload" type="checkbox" checked>显示示例参数</label><button id="clear-records" title="清空浏览器已完成历史；在途调用保留">清空本地记录</button><span class="toolbar-note">APP 示例调用 · RPC observationId 仅端内关联</span></div>
  <div id="panel-content" class="panel-content"></div>
  <div class="console-drawer"><div class="drawer-title">Console <span class="muted">最近记录</span><span>RPC / APP / TRANSPORT · 来源分别标识</span></div><div id="console-preview"></div></div>
  <footer class="statusbar"><span id="call-count">0 calls</span><span id="pending-count">0 pending</span><span id="node-state">Node snapshot…</span><span>公开事件 + 显式应用插桩 · 真实连接</span></footer>
 </section>
</main>`;
